name: "DAST Analysis SARIF Report"
on: [push]

jobs:
  soos_dast_analysis_example:
    name: A job to test new action
    runs-on: ubuntu-latest
    container:
      image: soosio/dast:latest
    steps:
      - name: Run SOOS DAST Analysis
        id: soos-dast-analysis
        working-directory: /zap
        run: |
          python3 main.py --clientId="$client_id" --apiKey="$api_key" --projectName="$project_name" --scanMode="$scan_mode" --apiURL="$api_url" --branchName="$branch_name" --commitHash="$commit_hash" --sarif=True --gpat="$gpat" $target_url
        env:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: ${{ github.repository }}
          branch_name: ${{ github.ref }}
          commit_hash: ${{ github.sha }}
          scan_mode: 'baseline'
          api_url: "https://api.soos.io/api/"
          target_url: "https://brokencrystals.com/"
          gpat: ${{ secrets.SOOS_GITHUB_PAT }}
